In [1]:
#Import NumPy library
import numpy as np

## Datatypes & Attibutes

In [4]:
# Main NumPy DataType is ndarray
# 1 dimension = Vector
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
# More than one dimension = Matrix
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15],
               [16,17,18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
#Number of dimensions of arrays
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [17]:
# Data types in the arrays
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [19]:
# Number of elements in the array
a1.size, a2.size, a3.size

(3, 6, 18)

In [20]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
# Create a DataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [2]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [4]:
sample_array.dtype

dtype('int32')

In [6]:
# shitf + tab con el cursor dentro de los parentesis muestra docstring(info) de la función.
ones = np.ones((2,3))
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
ones.dtype

dtype('float64')

In [9]:
type(ones)

numpy.ndarray

In [10]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [45]:
random_array = np.random.randint(0 ,10,size=(3,5))
random_array

array([[7, 2, 8, 6, 4],
       [5, 8, 4, 5, 0],
       [2, 1, 8, 1, 9]])

In [46]:
random_array.size

15

In [47]:
random_array.shape

(3, 5)

In [56]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.60761196, 0.32973915, 0.9611307 ],
       [0.77532689, 0.63502157, 0.65595531],
       [0.07826356, 0.82802173, 0.55013939],
       [0.5121061 , 0.87827756, 0.24934492],
       [0.90982406, 0.77613586, 0.49430096]])

In [58]:
random_array2.shape

(5, 3)

In [59]:
from numpy import random

In [60]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.97706472, 0.43939488, 0.36504574],
       [0.00122707, 0.04813701, 0.803596  ],
       [0.40006402, 0.4942762 , 0.50957399],
       [0.62691851, 0.38687471, 0.28372676],
       [0.32335099, 0.71935837, 0.10135554]])

In [61]:
from numpy import random

In [2]:
# Pseudo-random numbers
# Permite generar siempre los mismo numeros aleatorios. Que no cambien en cada ejecucion.
np.random.seed(seed=43)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[4, 0, 1],
       [5, 0, 3],
       [1, 2, 7],
       [0, 3, 2],
       [9, 1, 2]])

In [69]:
random_array_4.shape

(5, 3)

In [73]:
np.random.seed(seed=7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [3]:
#Devolver los valores unicos de un array.
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 9])

## Viewing Arrays and Matrices

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1[0]

1

In [11]:
a2[0]

array([1. , 2. , 3.3])

In [12]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a3[0,0]

array([1, 2, 3])

In [14]:
a3[0,0,0]

1

In [15]:
a3[0,0,1]

2

In [16]:
a3[0,0,2]

3

In [17]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [23]:
from numpy import random

In [24]:
a4 = np.random.randint(10,size = (2,3,4,5))
a4

array([[[[2, 3, 5, 4, 4],
         [0, 5, 8, 0, 0],
         [9, 2, 0, 4, 4],
         [8, 9, 7, 4, 8]],

        [[5, 0, 3, 2, 9],
         [9, 0, 6, 5, 5],
         [5, 8, 7, 3, 6],
         [3, 2, 4, 2, 7]],

        [[3, 6, 8, 3, 6],
         [7, 4, 5, 3, 5],
         [3, 8, 3, 5, 1],
         [6, 0, 0, 7, 1]]],


       [[[3, 1, 5, 8, 0],
         [3, 6, 9, 4, 6],
         [7, 9, 4, 5, 8],
         [4, 7, 4, 2, 9]],

        [[6, 7, 8, 8, 1],
         [8, 9, 5, 5, 8],
         [6, 8, 3, 4, 2],
         [3, 1, 4, 2, 2]],

        [[1, 4, 5, 5, 0],
         [3, 4, 7, 1, 2],
         [7, 9, 3, 1, 1],
         [3, 6, 5, 9, 8]]]])

In [25]:
a4.shape

(2, 3, 4, 5)

In [26]:
a4.ndim

4

In [31]:
#sacar los 4 primeros numeros del penultimo vector
a4[1,1,0,:4]

array([6, 7, 8, 8])

In [35]:
#Get the four first numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[2, 3, 5, 4],
         [0, 5, 8, 0],
         [9, 2, 0, 4],
         [8, 9, 7, 4]],

        [[5, 0, 3, 2],
         [9, 0, 6, 5],
         [5, 8, 7, 3],
         [3, 2, 4, 2]],

        [[3, 6, 8, 3],
         [7, 4, 5, 3],
         [3, 8, 3, 5],
         [6, 0, 0, 7]]],


       [[[3, 1, 5, 8],
         [3, 6, 9, 4],
         [7, 9, 4, 5],
         [4, 7, 4, 2]],

        [[6, 7, 8, 8],
         [8, 9, 5, 5],
         [6, 8, 3, 4],
         [3, 1, 4, 2]],

        [[1, 4, 5, 5],
         [3, 4, 7, 1],
         [7, 9, 3, 1],
         [3, 6, 5, 9]]]])

## Manipulating & comparing arrays

### Arithmetic

In [36]:
a1

array([1, 2, 3])

In [37]:
ones = np.ones(3)

In [38]:
ones

array([1., 1., 1.])

In [39]:
a1 + ones

array([2., 3., 4.])

In [40]:
a1 - ones

array([0., 1., 2.])

In [41]:
a1 * ones

array([1., 2., 3.])

In [43]:
a1

array([1, 2, 3])

In [44]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [45]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
# How can you reshape a2 to be compatible with a3?
# search "Numpy Broadcasting" and "How to reshape numpy array"
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [48]:
a1

array([1, 2, 3])

In [49]:
ones

array([1., 1., 1.])

In [50]:
a1 / ones

array([1., 2., 3.])

In [51]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [52]:
# Floor division removes the decimals (round down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [53]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [54]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [55]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [56]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [57]:
np.add(a1, ones)

array([2., 3., 4.])

In [58]:
#Devuelve el resto de la division
a1 % 2

array([1, 0, 1], dtype=int32)

In [59]:
a1

array([1, 2, 3])

In [60]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [61]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation